---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-test2-7
  namespace: argocd
spec:
  destination:
    namespace: pr-test2-7
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "2.9.9"
        ingress:
          host: "pr-test2-7.nip.io"
      version: v3
    path: helm
    repoURL: https://github.com/yairaba/devops-toolkit.git
    targetRevision: test2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
