apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-previews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: proj-root-previews
  source:
    repoURL: https://github.com/yairaba/argocd-previews.git
    targetRevision: master
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: root-previews
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
